# -*- coding: utf-8 -*-
"""streamcipher.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16FmHBGQXGU-o6P4kpJbrZk0MWmocSyfa
"""

class KeyStream:
  def _init_(self,key1):
    self.next=key
  def rand(self):
    self.next = (1103515245*self.next + 12345)% 2**31
  def get_key_byte(self):
    return self.rand() % 256
  def encrypt(key,message):
    return bytes([message[i]^key.get_key_byte() for i in range(len(message))])
   
    key = KeyStream(10)
    message = "Hello World".encode()
    cipher = encrypt(key,message)
    print(cipher)
    key = keyStream(10)
    message = encrypt(key,cipher)
    print(key)
    for i in range(10):
      print(key.get_key_byte())